#!/bin/bash

readonly Old_Filesystem="@1"


function analysisArgs() {

  if [ ! -d $Old_Filesystem ] ; then
    echo "$Old_Filesystem is not a directiory." 1>&2
    exit 1
  fi
}


function exit_if_no_root_permission() {

  if [ "$(id -u)" != "0" ]; then
    echo "This script must be run with root permission!" 1>&2
    exit 1
  fi
}


function main() {

  analysisArgs "$@"

  exit_if_no_root_permission

}

main "$@"
